# SYNTAX
attribute                   = "gray_5"
keyword                     = "blue"
"keyword.directive"         = "blue"
namespace                   = "gray_2"
punctuation                 = "gray_6"
"punctuation.delimiter"     = "gray_6"
operator                    = "blue"
# special = "gray_1" issue color in file picker
"variable.other.member"     = "gray_1"
variable                    = "gray_1"
"variable.parameter"        = { fg = "gray_1" }
"variable.builtin"          = "gray_1"
type                        = "gray_1"
"type.builtin"              = "gray_1"
constructor                 = "gray_1"
function                    = "white"
"function.macro"            = "white"
"function.builtin"          = "white"
tag                         = "gray_6"
comment                     = "gray_5"
constant                    = "gray_1"
"constant.builtin"          = "gray_1"
string                      = "strings"
"constant.numeric"          = "orange"
"constant.character.escape" = "gray_1"
label                       = "gray_1"


# INTERFACE
"ui.background"                   = { fg = "platinum", bg = "dark_gray_4" }
"ui.background.separator"         = { fg = "" } # file picker separator
"ui.cursor"                       = { fg = "gray_3", bg = "dark_gray_1", underline = { color = "white", style = "line"} }
"ui.cursor.normal"                = { fg = "gray_3", bg = "dark_gray_1", underline = { color = "white", style = "line"} }
"ui.cursor.insert"                = { fg = "gray_3", bg = "dark_gray_1", underline = { color = "white", style = "line"} }
"ui.cursor.select"                = { fg = "gray_3", bg = "dark_gray_1", underline = { color = "white", style = "line"} }
"ui.cursor.match"                 = { fg = "gray_3", underline = { color = "white", style = "line"} }
"ui.cursor.primary"               = { fg = "gray_3", bg = "dark_gray_1", underline = { color = "white", style = "line"} }
"ui.cursor.primary.normal"        = { fg = "gray_3", bg = "dark_gray_1", underline = { color = "white", style = "line"} }
"ui.cursor.primary.insert"        = { fg = "gray_3", bg = "dark_gray_1", underline = { color = "white", style = "line"} }
"ui.cursor.primary.select"        = { fg = "gray_3", bg = "dark_gray_1", underline = { color = "white", style = "line"} }
"ui.debug.breakpoint"             = { fg = "gray_4" }
"ui.debug.active"                 = { fg = "gray_7"}
"ui.gutter"                       = { fg = "gray_4" }
"ui.gutter.selected"              = { fg = "gray_4" }
"ui.highlight.frameline"          = { fg = "", bg = "" }
"ui.linenr"                       = { fg = "gray_4" }
"ui.linenr.selected"              = { fg = "black", bg = "green" }
"ui.statusline"                   = { fg = "black", bg = "green" }
"ui.statusline.inactive"          = { fg = "gray_4", bg = "dark_gray_2" }
"ui.statusline.normal"            = { fg = "black", bg = "green" }
"ui.statusline.insert"            = { fg = "black", bg = "green" }
"ui.statusline.select"            = { fg = "black", bg = "green" }
"ui.statusline.separator"         = { fg = ""}
"ui.popup"                        = { fg = "platinum", bg = "dark_gray_2" }
"ui.popup.info"                   = { fg = "green" }
"ui.window"                       = { fg = "gray_4" }
"ui.help"                         = { fg = "green" }
"ui.text"                         = { fg = "platinum"  }
"ui.text.focus"                   = { fg = "black", bg = "green" }
"ui.text.inactive"                = { fg = "gray_4" }
"ui.text.info"                    = { fg = "green" }
"ui.virtual.ruler"                = { bg = "dark_gray_3" }
"ui.virtual.whitespace"           = { fg = "darker_green" }
"ui.virtual.indent-guide"         = { fg = "dark_gray_2" }
"ui.virtual.inlay-hint"           = { fg = "gray_1", underline = { color = "green", style = "line"} }
"ui.virtual.inlay-hint.parameter" = { fg = "gray_1", underline = { color = "green", style = "line"}  }
"ui.virtual.inlay-hint.type"      = { fg = "gray_1", underline = { color = "green", style = "line"} }
"ui.virtual.wrap"                 = { fg = "gray_4" }
"ui.menu"                         = { fg = "green", bg = "dark_gray_2" }
"ui.menu.selected"                = { fg = "black", bg = "green" }
"ui.menu.scroll"                  = { fg = "green", bg = "dark_gray_2" }
"ui.selection"                    = { fg = "gray_3", bg = "dark_gray_1" }
"ui.selection.primary"            = { fg = "gray_3", bg = "dark_gray_1" }
"ui.highlight"                    = { fg = "black", bg = "dark_gray_2" }
"ui.cursorline.primary"           = { bg = "dark_gray_1" }
"ui.cursorline.secondary"         = { bg = "dark_gray_2" }
"ui.cursorcolumn.primary"         = { bg = "dark_gray_1" }
"ui.cursorcolumn.secondary"       = { bg = "dark_gray_2" }
"error"                           = { fg = "gray_7" }
"info"                            = { fg = "gray_7" }
"hint"                            = { fg = "gray_7" }
"diagnostic"                      = { fg = "gray_7" }
"diagnostic.hint"                 = { fg = "" } # Inline word color (hint, info, warning, error) not need
"diagnostic.info"                 = { fg = "" }
"diagnostic.warning"              = { fg = "" }
"diagnostic.error"                = { fg = "" }


[palette]
# from light to dark
white        = "#ffffff"
platinum     = "#e2e2e2"
dark_gray_1  = "#303030"
dark_gray_2  = "#262626"
dark_gray_3  = "#202020"
dark_gray_4  = "#1e1e1e"
gray_1       = "#b2b2b2"
gray_2       = "#a8a8a8"
gray_3       = "#9d9d9d"
gray_4       = "#818181"
gray_5       = "#606060"
gray_6       = "#545454"
gray_7       = "#4e4e4e"
black        = "#000000"

# colored
green        = "#19cc83"
darker_green = "#1a8a5d"
strings      = "#86d998" # green
red          = "#9a1c1c"
orange       = "#f7b786"
blue         = "#a4ccfe"